MOD_UAESGCM_DIR := $(USERMOD_DIR)

CFLAGS_USERMOD += -DMICROPY_PY_UAESGCM
CFLAGS_USERMOD += -I$(MOD_UAESGCM_DIR)

SRC_USERMOD += $(MOD_UAESGCM_DIR)/AesGCM.c
SRC_USERMOD += $(MOD_UAESGCM_DIR)/modaesgcm.c
